FROM archlinux

RUN pacman -Syq --noconfirm python-pip clang git git-lfs openssh cmake ninja gcc gdb nodejs yarn
RUN pip install cmakelang

RUN pacman -Syq --noconfirm python2
RUN pip install mkdocs-material
